import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import { VitePWA } from "vite-plugin-pwa";
import path from "path";

// https://vitejs.dev/config/
export default defineConfig(() => ({
  server: {
    host: "::",
    port: 8080,
    hmr: {
      overlay: false,
    },
  },
  plugins: [
    react(),
    // Generates dist/manifest.webmanifest, dist/sw.js and the registration
    // script at build time. Icons and splash screens are produced by
    // scripts/generate-pwa-assets.py; regenerate them if the logo changes.
    VitePWA({
      registerType: "autoUpdate",
      // Everything under public/ is copied to dist/; only these are worth
      // precaching. Icons and favicons are small and make the app installable
      // offline. (iOS launch images are not generated by default; see
      // scripts/generate-pwa-assets.py.)
      includeAssets: ["favicon.ico", "favicon-32.png", "icons/*.png", "robots.txt"],
      manifest: {
        id: "/",
        name: "Spot The Fallacy",
        short_name: "Spot Fallacy",
        description:
          "Practice spotting logical fallacies with 40+ fallacies and 120+ short real-world questions. Instant explanations, a daily 5-question challenge, and progress that stays on your device.",
        start_url: "/",
        scope: "/",
        display: "standalone",
        background_color: "#ffffff",
        theme_color: "#ffffff",
        lang: "en",
        dir: "ltr",
        categories: ["education", "productivity"],
        icons: [
          { src: "/icons/pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "/icons/pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "/icons/pwa-maskable-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        globPatterns: ["**/*.{js,css,html,ico,webmanifest}"],
        // Single-page app: serve the shell for any deep link while offline.
        navigateFallback: "/index.html",
        cleanupOutdatedCaches: true,
      },
    }),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    rollupOptions: {
      output: {
        // Keep the framework and the third-party kit in their own long-lived
        // chunks so a copy or data change does not force players to
        // re-download them. React and friends must stay together and must not
        // import anything from `vendor` (radix does import react), otherwise
        // rollup reports circular chunks.
        manualChunks(id) {
          if (!id.includes("node_modules")) return undefined;
          if (/[\\/]node_modules[\\/](react|react-dom|scheduler)[\\/]/.test(id)) {
            return "react";
          }
          return "vendor";
        },
      },
    },
  },
}));
