#!/usr/bin/env python3
"""
Generate the PWA icon set from public/images/logo.png.

The source logo is a white square containing two stacked bands of artwork: the
mark (magnifier and check) on top and the wordmark ("SPOT THE FALLACY") below.
Home screen icons use the mark alone, because a wordmark is unreadable at icon
sizes and the home screen already prints the app name underneath.

Run from the repo root after changing the logo:

    python3 scripts/generate-pwa-assets.py               # public/icons/*
    python3 scripts/generate-pwa-assets.py --ios-splash   # + public/splash/*

The Android/Chrome/desktop splash screen is generated by the browser from the
manifest, so it needs no assets. iOS ignores the manifest and only shows splash
art if given one image per exact device resolution, which is 20 files and over
a megabyte. That is off by default; pass --ios-splash and paste the printed
`apple-touch-startup-image` block into index.html if you want it.
"""
import shutil
import subprocess
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "public/images/logo.png"
ICON_DIR = ROOT / "public/icons"
SPLASH_DIR = ROOT / "public/splash"
BACKGROUND = (255, 255, 255)

# Physical pixels, portrait. `landscape` adds the rotated variant; it is set for
# tablets only, because they get rotated constantly and a missing match shows as
# a blank launch screen. Phones launch portrait in practice.
SPLASH_DEVICES = [
    # (width, height, dpr, landscape, label)
    (750, 1334, 2, False, "iPhone SE / 8"),
    (828, 1792, 2, False, "iPhone XR / 11"),
    (1125, 2436, 3, False, "iPhone X / XS / 11 Pro / 12 mini / 13 mini"),
    (1170, 2532, 3, False, "iPhone 12 / 13 / 14"),
    (1179, 2556, 3, False, "iPhone 14 Pro / 15 / 15 Pro / 16"),
    (1206, 2622, 3, False, "iPhone 16 Pro"),
    (1242, 2688, 3, False, "iPhone XS Max / 11 Pro Max"),
    (1284, 2778, 3, False, "iPhone 12 / 13 Pro Max / 14 Plus"),
    (1290, 2796, 3, False, "iPhone 14 Pro Max / 15 Plus"),
    (1320, 2868, 3, False, "iPhone 16 Pro Max"),
    (1536, 2048, 2, True, "iPad 9.7 / mini"),
    (1620, 2160, 2, True, "iPad 10.2"),
    (1640, 2360, 2, True, "iPad Air 10.9 / 11"),
    (1668, 2388, 2, True, "iPad Pro 11"),
    (2048, 2732, 2, True, "iPad Pro 12.9"),
]

# How much of the canvas the mark should span.
ICON_CONTENT = 0.78
# Maskable icons are cropped by the launcher's mask, so keep the mark well
# inside the safe circle.
MASKABLE_CONTENT = 0.60
APPLE_TOUCH_CONTENT = 0.80

# Splash composition, as a fraction of the shorter canvas side.
SPLASH_MARK_WIDTH = 0.26
SPLASH_GAP = 0.04
SPLASH_NAME_WIDTH = 0.54


def flatten_background(image: Image.Image, threshold: int = 238) -> Image.Image:
    """Snap near-white pixels to pure white.

    The source logo is a JPEG, so its "white" background is full of compression
    noise. Left alone that noise survives quantisation and dominates the file
    size; flattening it also removes the faint grey mottling behind the art.
    """
    pixels = image.load()
    width, height = image.size
    for y in range(height):
        for x in range(width):
            if min(pixels[x, y]) >= threshold:
                pixels[x, y] = (255, 255, 255)
    return image


def save_png(image: Image.Image, path: Path) -> None:
    """Write a PNG, shrinking it to a palette when a compressor is available."""
    image.save(path, optimize=True)
    if shutil.which("pngquant"):
        temp = path.with_suffix(".quantised.png")
        result = subprocess.run(
            ["pngquant", "--force", "--quality=65-95", "--strip", "--output", str(temp), str(path)],
            capture_output=True,
        )
        if result.returncode == 0 and temp.exists():
            temp.replace(path)
            return
        temp.unlink(missing_ok=True)
    image.quantize(colors=256, method=Image.MEDIANCUT, dither=Image.NONE).save(
        path, optimize=True
    )


def ink_bands(image: Image.Image, gap_tolerance: int = 6):
    """Split the artwork into stacked bands separated by blank rows."""
    width, height = image.size
    pixels = image.load()

    def row_has_ink(y: int) -> bool:
        return any(sum(pixels[x, y]) / 3 < 240 for x in range(0, width, 2))

    bands = []
    start = None
    blank_run = 0
    for y in range(height):
        if row_has_ink(y):
            if start is None:
                start = y
            blank_run = 0
        elif start is not None:
            blank_run += 1
            if blank_run > gap_tolerance:
                bands.append((start, y - blank_run))
                start = None
    if start is not None:
        bands.append((start, height - 1))
    return bands


def ink_bbox(image: Image.Image, top: int, bottom: int):
    """Column extents of the ink inside a horizontal band."""
    width = image.size[0]
    pixels = image.load()
    columns = [
        x
        for x in range(width)
        if any(sum(pixels[x, y]) / 3 < 240 for y in range(top, bottom + 1, 2))
    ]
    if not columns:
        raise SystemExit(f"band {top}-{bottom} has no ink")
    return (columns[0], top, columns[-1] + 1, bottom + 1)


def fit(band: Image.Image, box: int) -> Image.Image:
    """Scale a band so its longest side is `box` pixels, preserving aspect."""
    scale = box / max(band.size)
    size = (max(1, round(band.size[0] * scale)), max(1, round(band.size[1] * scale)))
    return band.resize(size, Image.LANCZOS)


def icon(mark: Image.Image, size: int, content: float) -> Image.Image:
    canvas = Image.new("RGB", (size, size), BACKGROUND)
    scaled = fit(mark, round(size * content))
    canvas.paste(scaled, ((size - scaled.size[0]) // 2, (size - scaled.size[1]) // 2))
    return canvas


def splash(mark: Image.Image, name: Image.Image, width: int, height: int) -> Image.Image:
    canvas = Image.new("RGB", (width, height), BACKGROUND)
    short = min(width, height)

    mark_scaled = fit(mark, round(short * SPLASH_MARK_WIDTH))
    name_scaled = fit(name, round(short * SPLASH_NAME_WIDTH))
    gap = round(short * SPLASH_GAP)

    block_height = mark_scaled.size[1] + gap + name_scaled.size[1]
    top = (height - block_height) // 2

    canvas.paste(mark_scaled, ((width - mark_scaled.size[0]) // 2, top))
    canvas.paste(
        name_scaled,
        ((width - name_scaled.size[0]) // 2, top + mark_scaled.size[1] + gap),
    )
    return canvas


def startup_link(width: int, height: int, dpr: int) -> str:
    query = (
        f"(device-width: {width // dpr}px) and (device-height: {height // dpr}px) "
        f"and (-webkit-device-pixel-ratio: {dpr})"
    )
    return (
        f'    <link rel="apple-touch-startup-image" '
        f'href="/splash/apple-splash-{width}-{height}.png" media="{query}" />'
    )


def clean(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for stale in directory.glob("*.png"):
        stale.unlink()


def main() -> None:
    logo = Image.open(SOURCE).convert("RGB")
    bands = ink_bands(logo)
    if len(bands) < 2:
        raise SystemExit(f"expected a mark and a wordmark in {SOURCE}, found {len(bands)} band(s)")

    mark = flatten_background(logo.crop(ink_bbox(logo, *bands[0])))
    name = flatten_background(logo.crop(ink_bbox(logo, *bands[-1])))
    print(f"mark {mark.size} from rows {bands[0]}, wordmark {name.size} from rows {bands[-1]}")

    clean(ICON_DIR)

    written = []
    for filename, image in [
        ("pwa-192x192.png", icon(mark, 192, ICON_CONTENT)),
        ("pwa-512x512.png", icon(mark, 512, ICON_CONTENT)),
        ("pwa-maskable-512x512.png", icon(mark, 512, MASKABLE_CONTENT)),
        ("apple-touch-icon.png", icon(mark, 180, APPLE_TOUCH_CONTENT)),
    ]:
        path = ICON_DIR / filename
        save_png(image, path)
        written.append(path)

    if "--ios-splash" not in sys.argv:
        total = sum(p.stat().st_size for p in written)
        print(f"\n{len(written)} icons, {total // 1024} KB total")
        return

    clean(SPLASH_DIR)
    links = []
    for width, height, dpr, landscape, label in SPLASH_DEVICES:
        variants = [(width, height)]
        if landscape:
            variants.append((height, width))
        for w, h in variants:
            path = SPLASH_DIR / f"apple-splash-{w}-{h}.png"
            save_png(splash(mark, name, w, h), path)
            written.append(path)
            links.append(startup_link(w, h, dpr))
        print(f"  {label}: {width}x{height}{' + landscape' if landscape else ''}")

    total = sum(p.stat().st_size for p in written)
    print(f"\n{len(written)} files, {total // 1024} KB total")

    print("\n--- paste into index.html, before </head> ---")
    print("\n".join(links))


if __name__ == "__main__":
    main()
