"""Phase 4: add 10 missing fallacies (43 total), 30 questions (129 total),
wire them through every enhancedData map, and make confusion pairs symmetric."""
import json
from collections import OrderedDict

NEW = [
    dict(name="Slippery Slope", category="Causal Errors",
         description="Claiming that one small step must trigger a chain of events ending in disaster, without proving that any of the links in the chain actually hold.",
         examples=["If we give students one red-pen day, soon they'll demand no grades at all, and the whole school will collapse into chaos.",
                   "Banning one harmful app will lead to banning every app, and then the entire internet will be shut down."],
         key_terms=["chain reaction", "small step", "cascade", "extreme outcome", "unproven chain"],
         confused=["Appeal to Probability", "Post Hoc", "Appeal to Fear"],
         diagram=["One small step taken", "Unproven event chain", "Disaster declared"],
         valid="A valid argument proves each link in the chain. For example: 'Schools that allowed red-pen days saw grade disputes rise, which then led to policy changes.'"),
    dict(name="Appeal to Fear", category="Emotional Manipulation",
         description="Scaring someone into agreement by describing what will happen if they don't agree, instead of giving a reason the claim is true.",
         examples=["Vote for me or your family will not be safe.",
                   "Buy this security system now, or tonight could be the worst night of your life."],
         key_terms=["fear", "threat", "scare tactic", "danger", "intimidation"],
         confused=["Appeal to Emotion", "Manufactured Consensus"],
         diagram=["Scary outcome painted", "Fear replaces evidence", "Claim accepted"],
         valid="A valid case shows the danger is real and the response works. For example: 'Break-ins on this street rose 30% last year, and this lock blocks the entry method used.'"),
    dict(name="Argument to Moderation", category="Faulty Logic",
         description="Assuming the truth must sit exactly halfway between two positions, just because the positions exist.",
         examples=["One expert says the bridge holds 10 tons and another says 2 tons, so it surely holds 6 tons.",
                   "You say the test is Tuesday and I say Thursday, so it must be Wednesday."],
         key_terms=["middle ground", "compromise", "moderation", "halfway", "split the difference"],
         confused=["False Dilemma", "Nirvana Fallacy"],
         diagram=["Two sides argued", "Split the difference", "Midpoint called true"],
         valid="A valid conclusion follows the evidence, not the midpoint. For example: 'The dose makes the poison: safe at 5mg, harmful at 50mg.'"),
    dict(name="Post Hoc", category="Causal Errors",
         description="Because one thing happened after another, the first thing must have caused the second.",
         examples=["I wore these socks and we won the game, so the socks made us win.",
                   "The rooster crowed and then the sun came up, so the rooster raises the sun."],
         key_terms=["after this", "cause", "sequence", "coincidence", "because of"],
         confused=["Magical Thinking", "Texas Sharpshooter", "Slippery Slope"],
         diagram=["A happens, then B", "Other causes ignored", "A blamed for B"],
         valid="A valid causal claim checks other explanations. For example: 'Sales rose after the ads ran, and we ruled out the holiday spike.'"),
    dict(name="Loaded Question", category="Faulty Logic",
         description="A question built on an unproven assumption, so that answering it directly makes you look guilty.",
         examples=["Have you stopped copying your homework?",
                   "Why is your whole family so bad at driving?"],
         key_terms=["presuppose", "assumption", "trap", "loaded", "entrapment"],
         confused=["Begging the Question", "Straw Man"],
         diagram=["Question hides a claim", "Any answer looks guilty", "Assumption 'proven'"],
         valid="A valid question asks one thing without smuggling in assumptions. For example: 'Did you copy the homework, yes or no?'"),
    dict(name="Guilt by Association", category="Personal Attack",
         description="Rejecting a person or idea because of who else is connected to it, rather than on its own merits.",
         examples=["That policy must be bad, since the chess club supports it.",
                   "You can't trust her research; her neighbor was once arrested."],
         key_terms=["association", "guilt", "group", "company keeps", "linked to"],
         confused=["Ad Hominem", "Argument from Motive", "Scapegoat"],
         diagram=["Group B backs X", "B is disliked", "So X is rejected"],
         valid="A valid argument judges the idea itself. For example: 'Set aside who endorses it; here is what the policy actually does.'"),
    dict(name="Motte-and-Bailey", category="Misrepresentation",
         description="Defending a bold, exciting claim by quietly retreating to a small, safe one whenever anyone pushes back.",
         examples=["'Homework should be banned' becomes 'teachers could assign a little less' the moment someone objects.",
                   "'This supplement cures illness' becomes 'I only said it supports wellness' when questioned."],
         key_terms=["retreat", "bold claim", "safe claim", "walk back", "reposition"],
         confused=["Equivocation", "Moving the Goalposts"],
         diagram=["Bold claim made", "Pressed for evidence", "Retreat to safe claim"],
         valid="A valid debater states one claim and defends that exact claim. For example: 'My claim is homework should be capped at one hour; here is the study behind it.'"),
    dict(name="Appeal to AI Authority", category="False Authority",
         description="Treating an answer as true just because an AI tool produced it, without checking whether the tool is reliable for that question.",
         examples=["The chatbot said this stock will triple, so it must be a good investment.",
                   "My essay must be correct because an AI wrote it."],
         key_terms=["AI", "algorithm", "chatbot", "automation", "model"],
         confused=["Appeal to Authority", "Appeal to Novelty"],
         diagram=["The AI says X", "Reliability unproven", "X treated as fact"],
         valid="A valid use of AI verifies the output. For example: 'The model suggested X; the cited study supports X within these limits.'"),
    dict(name="Manufactured Consensus", category="Emotional Manipulation",
         description="Faking the appearance of wide agreement with bots, fake reviews, or paid supporters, then treating that fake popularity as proof.",
         examples=["Five thousand identical five-star reviews appear overnight, so the product must be great.",
                   "One campaign hires a thousand accounts to repeat its slogan, so the slogan must be popular."],
         key_terms=["bots", "fake reviews", "astroturf", "paid actors", "artificial support"],
         confused=["Appeal to Popularity", "Appeal to Fear"],
         diagram=["Fake crowd created", "Agreement looks huge", "Doubters give in"],
         valid="A valid consensus comes from verifiable, independent voices. For example: 'Ten unrelated labs replicated the result.'"),
    dict(name="Fallacy of Division", category="Faulty Logic",
         description="Assuming that whatever is true of a whole must also be true of each of its parts.",
         examples=["The airplane weighs 400 tons, so every bolt must weigh 400 tons.",
                   "The team is unbeatable, so the newest substitute must be unbeatable too."],
         key_terms=["whole to part", "each member", "division", "distribute", "parts share"],
         confused=["Fallacy of Composition", "Overgeneralization"],
         diagram=["Whole has trait T", "Parts examined", "Each part called T"],
         valid="A valid inference tests the parts directly. For example: 'The team is strong, but the new keeper has played one game; here is his record.'"),
]

QUESTIONS = [
    ("Slippery Slope",
     "The student council proposes adding one more vending machine. A teacher responds, 'First it's vending machines, then it's a soda empire in every hallway, and within two years this school will exist only to sell snacks.' This is an example of...",
     ["Slippery Slope", "Appeal to Fear", "Overgeneralization", "Red Herring"]),
    ("Slippery Slope",
     "A city council approves painting one new bike lane. A local columnist warns, 'This is how it starts. Soon cars will be banned entirely and nobody will be able to drive to work.' This is an example of...",
     ["Slippery Slope", "False Dilemma", "Appeal to Authority", "Straw Man"]),
    ("Slippery Slope",
     "A gamer's parents consider limiting gaming to one hour on school nights. He argues, 'If you cut me to one hour today, next month it'll be zero, and then you'll be selling my console.' This is an example of...",
     ["Slippery Slope", "Appeal to Fear", "False Dilemma", "Sunk-Cost Fallacy"]),
    ("Appeal to Fear",
     "A home security ad shows a masked figure lurking outside a window while a narrator says, 'This could be your house tonight. Call now.' Instead of explaining the product, the ad persuades with...",
     ["Appeal to Fear", "Appeal to Authority", "Appeal to Popularity", "Non Sequitur"]),
    ("Appeal to Fear",
     "A class president candidate ends every speech with, 'Vote for me, or watch this school spiral into chaos.' The candidate is relying on...",
     ["Appeal to Fear", "Appeal to Popularity", "Straw Man", "Ad Hominem"]),
    ("Appeal to Fear",
     "An email warns, 'Your files WILL be encrypted by hackers unless you download our protector immediately,' and never explains what the product actually does. The email's persuasion is...",
     ["Appeal to Fear", "Appeal to Novelty", "False Dilemma", "Cherry Picking"]),
    ("Argument to Moderation",
     "One historian says a battle took place in 1815, another says 1850. A student concludes, 'The truth is in the middle, so it happened around 1832.' This is an example of...",
     ["Argument to Moderation", "Equivocation", "Appeal to Authority", "Non Sequitur"]),
    ("Argument to Moderation",
     "One friend says a movie ends happily, another says it ends tragically. A third, who hasn't watched it, says, 'It must end both ways at once.' This is an example of...",
     ["Argument to Moderation", "False Dilemma", "Equivocation", "Begging the Question"]),
    ("Argument to Moderation",
     "A chef says the soup needs no salt. A customer says it needs a whole cup. A judge, without tasting it, declares, 'The answer is half a cup.' The judge committed...",
     ["Argument to Moderation", "Appeal to Authority", "Non Sequitur", "Overgeneralization"]),
    ("Post Hoc",
     "A soccer player scores right after switching to orange laces, then refuses to play without them, insisting the laces score the goals. This is an example of...",
     ["Post Hoc", "Overgeneralization", "Gambler's Fallacy", "Slippery Slope"]),
    ("Post Hoc",
     "Every time Maya washes her car, it rains the next day. She concludes, 'My car washes cause rain.' This is an example of...",
     ["Post Hoc", "Texas Sharpshooter", "Magical Thinking", "Appeal to Probability"]),
    ("Post Hoc",
     "The school installed new clocks on Monday and test scores rose on Friday. The principal announces, 'The clocks clearly raised our scores,' ignoring the new tutoring program. This is an example of...",
     ["Post Hoc", "Cherry Picking", "Texas Sharpshooter", "Red Herring"]),
    ("Loaded Question",
     "A reporter asks a mayor, 'Why do you keep ignoring the city's housing crisis?' The mayor has actually pushed three housing bills. The question is an example of...",
     ["Loaded Question", "Begging the Question", "Ad Hominem", "Red Herring"]),
    ("Loaded Question",
     "'Have you stopped leaving your trash in my locker?' a student demands of a classmate, who cannot answer yes or no without sounding guilty. This is an example of...",
     ["Loaded Question", "False Dilemma", "Tu Quoque", "Straw Man"]),
    ("Loaded Question",
     "During a debate, one candidate asks the other, 'So when did you decide you were completely out of touch with voters?' This is an example of...",
     ["Loaded Question", "Ad Hominem", "Moving the Goalposts", "Non Sequitur"]),
    ("Guilt by Association",
     "'You like pineapple on pizza? The math team captain likes it too, and everyone knows the math team cheats.' The speaker's reasoning is an example of...",
     ["Guilt by Association", "Ad Hominem", "Scapegoat", "Red Herring"]),
    ("Guilt by Association",
     "A company rejects a job applicant because one of her references once attended school with a famous fraudster. The company is committing...",
     ["Guilt by Association", "Ad Hominem", "Non Sequitur", "Appeal to Authority"]),
    ("Guilt by Association",
     "'That charity can't be trustworthy, since a rock star everyone distrusts donated to it.' This dismissal is an example of...",
     ["Guilt by Association", "Argument from Motive", "Appeal to Money" if False else "Appeal to Novelty", "Straw Man"]),
    ("Motte-and-Bailey",
     "A student announces, 'Homework should be banned forever.' When challenged, she says, 'All I meant was teachers could assign slightly less sometimes.' The retreat is an example of...",
     ["Motte-and-Bailey", "Moving the Goalposts", "Equivocation", "Red Herring"]),
    ("Motte-and-Bailey",
     "A streamer claims, 'My method guarantees you'll go pro.' When viewers demand proof, he says, 'I just meant practicing helps a little.' This is an example of...",
     ["Motte-and-Bailey", "Begging the Question", "Appeal to Novelty", "False Dilemma"]),
    ("Motte-and-Bailey",
     "An ad declares, 'This drink cures tiredness.' When regulators complain, the company says, 'We only meant it contains caffeine, which reduces drowsiness.' The switch is an example of...",
     ["Motte-and-Bailey", "Equivocation", "Cherry Picking", "Appeal to Authority"]),
    ("Appeal to AI Authority",
     "'The chatbot says this crypto coin will 10x, so I'm investing my savings.' Being convinced purely because an AI said so is an example of...",
     ["Appeal to AI Authority", "Appeal to Authority", "Appeal to Novelty", "Gambler's Fallacy"]),
    ("Appeal to AI Authority",
     "A student submits an essay and tells the teacher, 'It must be accurate, because an AI wrote it.' This reasoning is an example of...",
     ["Appeal to AI Authority", "Begging the Question", "Appeal to Authority", "Non Sequitur"]),
    ("Appeal to AI Authority",
     "'The recommendation algorithm promoted this news story, so it must be the most important story today.' This is an example of...",
     ["Appeal to AI Authority", "Appeal to Popularity", "Cherry Picking", "Appeal to Tradition"]),
    ("Manufactured Consensus",
     "A product collects 5,000 five-star reviews in two days, all written in the same style by accounts created the same week. Believing 'everyone loves it' is falling for...",
     ["Manufactured Consensus", "Appeal to Popularity", "Appeal to Novelty", "Texas Sharpshooter"]),
    ("Manufactured Consensus",
     "A political group pays hundreds of accounts to post identical praise online, creating the look of massive support. Counting those posts as real support is an example of...",
     ["Manufactured Consensus", "Appeal to Popularity", "Cherry Picking", "Red Herring"]),
    ("Manufactured Consensus",
     "A restaurant's 'number one in the city!' banner comes from reviews its own staff wrote. Believing the banner is an example of...",
     ["Manufactured Consensus", "Appeal to Authority", "Appeal to Novelty", "Begging the Question"]),
    ("Fallacy of Division",
     "'This airplane weighs 400 tons, so every single bolt in it must weigh 400 tons too.' This is an example of...",
     ["Fallacy of Division", "Fallacy of Composition", "Overgeneralization", "Non Sequitur"]),
    ("Fallacy of Division",
     "'The orchestra is world-famous, so every musician in it must be world-famous.' This is an example of...",
     ["Fallacy of Division", "Fallacy of Composition", "Overgeneralization", "Equivocation"]),
    ("Fallacy of Division",
     "'Our team is the best in the league, so our newest substitute must be the best player too.' This is an example of...",
     ["Fallacy of Division", "Fallacy of Composition", "Overgeneralization", "Begging the Question"]),
]

# ---------- fallacies.json ----------
fallacies = json.load(open('src/data/fallacies.json'), object_pairs_hook=OrderedDict)
assert not (set(f['name'] for f in fallacies) & set(f['name'] for f in NEW)), "name collision"
for f in NEW:
    fallacies.append(OrderedDict([("name", f["name"]), ("description", f["description"]),
                                  ("examples", f["examples"])]))
json.dump(fallacies, open('src/data/fallacies.json', 'w'), indent=2)

# ---------- quiz-questions.json ----------
qs = json.load(open('src/data/quiz-questions.json'))
existing = set(q['question'] for q in qs)
for name, text, options in QUESTIONS:
    assert text not in existing, f"duplicate question: {text[:50]}"
    assert all(isinstance(o, str) for o in options)
    qs.append(OrderedDict([("fallacy_name", name), ("question", text),
                           ("options", options), ("correct_answer", options[0])]))
json.dump(qs, open('src/data/quiz-questions.json', 'w'), indent=2)
print(f"fallacies: {len(fallacies)}, questions: {len(qs)}")
